# Generated by Django 5.2 on 2026-07-26 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-created_at'], 'verbose_name': 'ملک', 'verbose_name_plural': 'املاک'},
        ),
        migrations.AlterModelOptions(
            name='propertyimage',
            options={'ordering': ['created_at'], 'verbose_name': 'تصویر ملک', 'verbose_name_plural': 'تصاویر املاک'},
        ),
        migrations.AddField(
            model_name='property',
            name='bathrooms',
            field=models.IntegerField(default=1, verbose_name='تعداد حمام'),
        ),
        migrations.AddField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(default=1, verbose_name='تعداد اتاق خواب'),
        ),
        migrations.AddField(
            model_name='property',
            name='floor_number',
            field=models.IntegerField(default=1, verbose_name='طبقه'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_elevator',
            field=models.BooleanField(default=False, verbose_name='آسانسور'),
        ),
        migrations.AddField(
            model_name='property',
            name='parking',
            field=models.BooleanField(default=False, verbose_name='پارکینگ'),
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.TextField(verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.DecimalField(decimal_places=2, help_text='متراژ', max_digits=10, verbose_name='متراژ'),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قیمت (تومان)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'آپارتمان'), ('villa', 'ویلا'), ('office', 'دفتر کار'), ('land', 'زمین')], default='apartment', max_length=20, verbose_name='نوع ملک'),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('available', 'موجود'), ('sold', 'فروخته شده'), ('rented', 'اجاره داده شده')], default='available', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(max_length=300, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='caption',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='توضیح تصویر'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(upload_to='properties/%Y/%m/%d/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property', verbose_name='ملک'),
        ),
    ]
