# Generated by Django 5.2 on 2026-07-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_property_options_alter_propertyimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='نمایش در املاک ویژه'),
        ),
        migrations.AddField(
            model_name='property',
            name='is_urgent',
            field=models.BooleanField(default=False, verbose_name='نمایش در فروش ویژه'),
        ),
    ]
