# Generated by Django 5.2 on 2026-07-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_is_featured_property_is_urgent'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='storage',
            field=models.BooleanField(default=False, verbose_name='انباری'),
        ),
        migrations.AddField(
            model_name='property',
            name='total_floors',
            field=models.IntegerField(default=1, verbose_name='کل طبقات'),
        ),
        migrations.AddField(
            model_name='property',
            name='yard_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='متراژ حیاط'),
        ),
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='متراژ'),
        ),
    ]
