# Generated by Django 5.2 on 2026-07-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_storage_property_total_floors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True, verbose_name='قیمت (تومان)'),
        ),
    ]
