# Generated by Django 5.2 on 2026-07-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_property_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='تعداد بازدید'),
        ),
    ]
